<a href="https://colab.research.google.com/github/newmantic/qr_decomposition/blob/main/qr_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def qr_decomposition(A):
    """
    Perform QR decomposition of a matrix A using the Gram-Schmidt process.

    Parameters:
    A (np.ndarray): The input matrix of shape (m, n).

    Returns:
    tuple: Q (np.ndarray), R (np.ndarray) where A = Q * R.
    """
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]

        # Compute the orthogonalized vector
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Testable example:
A = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1]])

Q, R = qr_decomposition(A)
print("Matrix Q:")
print(Q)
print("Matrix R:")
print(R)

# Verify that A = Q * R
A_reconstructed = np.dot(Q, R)
print("Reconstructed Matrix A:")
print(A_reconstructed)

Matrix Q:
[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
Matrix R:
[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
Reconstructed Matrix A:
[[1.00000000e+00 1.00000000e+00 4.02426802e-17]
 [1.00000000e+00 1.73428748e-19 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 1.00000000e+00]]


In [2]:
# example:
A_advanced = np.array([[12, -51, 4],
                       [6, 167, -68],
                       [-4, 24, -41]])

Q_advanced, R_advanced = qr_decomposition(A_advanced)
print("Advanced Matrix Q:")
print(Q_advanced)
print("Advanced Matrix R:")
print(R_advanced)

# Verify that A_advanced = Q_advanced * R_advanced
A_advanced_reconstructed = np.dot(Q_advanced, R_advanced)
print("Reconstructed Advanced Matrix A:")
print(A_advanced_reconstructed)

Advanced Matrix Q:
[[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]
Advanced Matrix R:
[[ 14.  21. -14.]
 [  0. 175. -70.]
 [  0.   0.  35.]]
Reconstructed Advanced Matrix A:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
